# Generated by Django 4.2.1 on 2023-05-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enterprise',
            new_name='project',
        ),
    ]
